/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:515186:
  appc.background(230);
} //_CODE_:window1:515186:

public void Materials(GDropList source, GEvent event) { //_CODE_:Material:261635:
 // materialChosen = Material.getSelectedText();
  firstHouse.updateHouse(Material.getSelectedText(),FoundationStrength.getValueI());
} //_CODE_:Material:261635:

public void foundationStrengthSlider(GSlider source, GEvent event) { //_CODE_:FoundationStrength:542419:
//  foundationStrength = FoundationStrength.getValueI();
  firstHouse.updateHouse(Material.getSelectedText(),FoundationStrength.getValueI());
} //_CODE_:FoundationStrength:542419:

public void materialLabelEvent(GTextField source, GEvent event) { //_CODE_:materialLabel:489327:
  
} //_CODE_:materialLabel:489327:

public void foundationStrengthLabelEvent(GTextField source, GEvent event) { //_CODE_:foundationStrengthLabel:391610:
  
} //_CODE_:foundationStrengthLabel:391610:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 300, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  Material = new GDropList(window1, 69, 39, 90, 120, 5, 10);
  Material.setItems(loadStrings("list_261635"), 2);
  Material.addEventHandler(this, "Materials");
  FoundationStrength = new GSlider(window1, 40, 111, 149, 40, 10.0);
  FoundationStrength.setLimits(50.0, 0.0, 100.0);
  FoundationStrength.setNumberFormat(G4P.DECIMAL, 2);
  FoundationStrength.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  FoundationStrength.setOpaque(false);
  FoundationStrength.addEventHandler(this, "foundationStrengthSlider");
  materialLabel = new GTextField(window1, 58, 3, 120, 30, G4P.SCROLLBARS_NONE);
  materialLabel.setText("Material");
  materialLabel.setOpaque(false);
  materialLabel.addEventHandler(this, "materialLabelEvent");
  foundationStrengthLabel = new GTextField(window1, 56, 75, 120, 30, G4P.SCROLLBARS_NONE);
  foundationStrengthLabel.setText("Foundation Strength");
  foundationStrengthLabel.setOpaque(false);
  foundationStrengthLabel.addEventHandler(this, "foundationStrengthLabelEvent");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GDropList Material; 
GSlider FoundationStrength; 
GTextField materialLabel; 
GTextField foundationStrengthLabel; 
